### ISSUE TITLE
add coveralls.io

### ISSUE THREAD

**Issue by sayanee** [webuildsg/bot#1]
will try again...

![screenshot 2016-06-20 13 39 05](https://cloud.githubusercontent.com/assets/413879/16184164/80d268c0-36ec-11e6-818e-b74afe66ab85.png)

hmmm why the bot repo is not coming up...

![screenshot 2016-06-20 13 41 12](https://cloud.githubusercontent.com/assets/413879/16184187/c364e550-36ec-11e6-8653-8dbd9dc1bb1c.png)

**Comment by kahwee** [comment]
Seems to be addable at my end. Thanks!
